"""
app.py
Full-Stack Assessment - Flask Backend
Handles: Sign-Up, Login, Dashboard, File Upload, File Download
"""

import os
import re
import urllib.parse  # Added to safely encode the password containing '@'
from datetime import datetime
from functools import wraps

from flask import (
    Flask, render_template, request, redirect,
    url_for, session, flash, send_from_directory, abort
)
import pymysql
import pymysql.cursors
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from dotenv import load_dotenv

load_dotenv()

# ------------------------------------------------------------------
# App configuration
# ------------------------------------------------------------------
app = Flask(__name__)
app.secret_key = os.getenv("SECRET_KEY", "dev-secret-key")

# Database configurations with fallback values
DB_HOST = os.getenv("MYSQL_HOST", "localhost")
DB_USER = os.getenv("MYSQL_USER", "root")

# Automatically handles 'vengat@123' or whatever password is provided
raw_password = os.getenv("MYSQL_PASSWORD", "vengat@123")
DB_PASSWORD = urllib.parse.quote_plus(raw_password) 

DB_NAME = os.getenv("MYSQL_DB", "fullstack_app")
DB_PORT = int(os.getenv("MYSQL_PORT", 3306))


def get_db_connection():
    """Open a new PyMySQL connection. Caller must close it."""
    return pymysql.connect(
        host=DB_HOST,
        user=DB_USER,
        password=raw_password, # PyMySQL connection uses raw string directly
        database=DB_NAME,
        port=DB_PORT,
        cursorclass=pymysql.cursors.DictCursor,
        autocommit=False,
    )

UPLOAD_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "uploads")
DOWNLOAD_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static", "downloads")
ALLOWED_EXTENSIONS = {"pdf", "png", "jpg", "jpeg"}
MAX_CONTENT_LENGTH = 5 * 1024 * 1024  # 5 MB per request

app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER
app.config["MAX_CONTENT_LENGTH"] = MAX_CONTENT_LENGTH

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(DOWNLOAD_FOLDER, exist_ok=True)

EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
MOBILE_REGEX = re.compile(r"^[0-9]{10}$")


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def allowed_file(filename: str) -> bool:
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


def login_required(view_func):
    @wraps(view_func)
    def wrapped(*args, **kwargs):
        if "user_id" not in session:
            flash("Please log in to continue.", "error")
            return redirect(url_for("login"))
        return view_func(*args, **kwargs)
    return wrapped


def create_test_download_file():
    """Create a sample file that users can download from the dashboard."""
    sample_path = os.path.join(DOWNLOAD_FOLDER, "sample_test_file.txt")
    if not os.path.exists(sample_path):
        with open(sample_path, "w") as f:
            f.write(
                "This is a sample test file for the Full-Stack Assessment.\n"
                "Generated by Flask backend.\n"
                f"Created at: {datetime.now()}\n"
            )


create_test_download_file()


# ------------------------------------------------------------------
# Routes: Sign-Up
# ------------------------------------------------------------------
@app.route("/", methods=["GET"])
def index():
    if "user_id" in session:
        return redirect(url_for("dashboard"))
    return redirect(url_for("login"))


@app.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        age = request.form.get("age", "").strip()
        address = request.form.get("address", "").strip()
        email = request.form.get("email", "").strip().lower()
        mobile = request.form.get("mobile", "").strip()
        password = request.form.get("password", "")
        confirm_password = request.form.get("confirm_password", "")

        # ---- Validation ----
        if not all([name, age, address, email, mobile, password, confirm_password]):
            flash("All fields are required.", "error")
            return redirect(url_for("signup"))

        if not age.isdigit() or not (1 <= int(age) <= 120):
            flash("Please enter a valid age.", "error")
            return redirect(url_for("signup"))

        if not EMAIL_REGEX.match(email):
            flash("Please enter a valid email address.", "error")
            return redirect(url_for("signup"))

        if not MOBILE_REGEX.match(mobile):
            flash("Mobile number must be exactly 10 digits.", "error")
            return redirect(url_for("signup"))

        if len(password) < 6:
            flash("Password must be at least 6 characters long.", "error")
            return redirect(url_for("signup"))

        if password != confirm_password:
            flash("Passwords do not match.", "error")
            return redirect(url_for("signup"))

        try:
            conn = get_db_connection()
            cur = conn.cursor()
        except Exception as db_err:
            flash(f"Database Connection Failed! Make sure MySQL is started. Error: {str(db_err)}", "error")
            return redirect(url_for("signup"))

        try:
            # Check duplicates
            cur.execute(
                "SELECT id FROM users WHERE email = %s OR mobile_number = %s",
                (email, mobile),
            )
            if cur.fetchone():
                flash("An account with this email or mobile number already exists.", "error")
                return redirect(url_for("signup"))

            password_hash = generate_password_hash(password)
            cur.execute(
                """INSERT INTO users (name, age, address, email, mobile_number, password_hash)
                   VALUES (%s, %s, %s, %s, %s, %s)""",
                (name, int(age), address, email, mobile, password_hash),
            )
            conn.commit()
            flash("Account created successfully! Please log in.", "success")
            return redirect(url_for("login"))
        except Exception as e:
            conn.rollback()
            flash(f"Something went wrong: {str(e)}", "error")
            return redirect(url_for("signup"))
        finally:
            cur.close()
            conn.close()

    return render_template("signup.html")


# ------------------------------------------------------------------
# Routes: Login / Logout
# ------------------------------------------------------------------
@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")

        if not email or not password:
            flash("Email and password are required.", "error")
            return redirect(url_for("login"))

        try:
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("SELECT * FROM users WHERE email = %s", (email,))
            user = cur.fetchone()
            cur.close()
            conn.close()
        except Exception as db_err:
            flash(f"Database Connection Failed: {str(db_err)}", "error")
            return redirect(url_for("login"))

        if user and check_password_hash(user["password_hash"], password):
            session["user_id"] = user["id"]
            session["user_name"] = user["name"]
            session["user_email"] = user["email"]
            flash(f"Welcome back, {user['name']}!", "success")
            return redirect(url_for("dashboard"))

        flash("Invalid email or password.", "error")
        return redirect(url_for("login"))

    return render_template("login.html")


@app.route("/logout")
def logout():
    session.clear()
    flash("You have been logged out.", "success")
    return redirect(url_for("login"))


# ------------------------------------------------------------------
# Routes: Dashboard
# ------------------------------------------------------------------
@app.route("/dashboard")
@login_required
def dashboard():
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute(
        "SELECT id, filename, file_type, upload_time FROM uploaded_files "
        "WHERE user_id = %s ORDER BY upload_time DESC",
        (session["user_id"],),
    )
    files = cur.fetchall()
    cur.close()
    conn.close()
    return render_template("dashboard.html", user_name=session.get("user_name"), files=files)


# ------------------------------------------------------------------
# Routes: File Download (test file)
# ------------------------------------------------------------------
@app.route("/download-test-file")
@login_required
def download_test_file():
    return send_from_directory(
        DOWNLOAD_FOLDER, "sample_test_file.txt", as_attachment=True
    )


# ------------------------------------------------------------------
# Routes: File Upload (two fields)
# ------------------------------------------------------------------
@app.route("/upload", methods=["POST"])
@login_required
def upload_files():
    user_id = session["user_id"]
    user_name = secure_filename(session.get("user_name", "user")).replace(" ", "_")

    uploaded_any = False
    conn = get_db_connection()
    cur = conn.cursor()

    for field_name in ("file1", "file2"):
        file = request.files.get(field_name)
        if not file or file.filename == "":
            continue

        if not allowed_file(file.filename):
            flash(f"{field_name}: only PDF, PNG, or JPEG files are allowed.", "error")
            continue

        ext = file.filename.rsplit(".", 1)[1].lower()
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        safe_original = secure_filename(file.filename)
        final_filename = f"{user_name}_{timestamp}_{safe_original}"

        filepath = os.path.join(app.config["UPLOAD_FOLDER"], final_filename)
        file.save(filepath)

        cur.execute(
            """INSERT INTO uploaded_files (user_id, filename, file_type, upload_time)
               VALUES (%s, %s, %s, %s)""",
            (user_id, final_filename, ext, datetime.now()),
        )
        uploaded_any = True

    conn.commit()
    cur.close()
    conn.close()

    if uploaded_any:
        flash("File(s) uploaded successfully.", "success")
    else:
        flash("No valid files were uploaded. Allowed types: PDF, PNG, JPEG.", "error")

    return redirect(url_for("dashboard"))


# ------------------------------------------------------------------
# Error handlers
# ------------------------------------------------------------------
@app.errorhandler(413)
def file_too_large(e):
    flash("File too large. Maximum allowed size is 5 MB.", "error")
    return redirect(url_for("dashboard"))


@app.errorhandler(404)
def not_found(e):
    return render_template("404.html"), 404


if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))
    debug_mode = os.getenv("FLASK_DEBUG", "true").lower() == "true"
    app.run(debug=debug_mode, host="0.0.0.0", port=port)